services:
  - type: web
    name: rexon-business-os
    env: node
    plan: starter
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        value: https://ramolmo.github.io
      - key: SUPABASE_URL
        value: https://pxejdzlrcesjepndgpyo.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_zhiBHjv-fhhEhy7wvX52AA_1sE0sSSL
      - key: TURSO_DATABASE_URL
        value: https://datafow-ramolmoaran.aws-ap-south-1.turso.io
